# Generated by Django 3.0.3 on 2020-07-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200727_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicAssist',
        ),
    ]
