# Generated by Django 3.0.6 on 2020-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_auto_20200811_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
