# Generated by Django 3.0.6 on 2020-08-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_auto_20200812_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='case_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='death_date',
            field=models.DateField(null=True),
        ),
    ]
